N: 230
f: 0.002
kon: 0.002
kext: 0.5
ktol: 0.015
koff1: 0.02
koff2: 0.01
kdloop: 0.01
kre: 0.001
seed_zero: 1999
timepoints: 100000
every: 10
gamma_k: 4
gamma_theta: 6200
intermediates: 
    - 8
    - 9
    - 12
    - 15
    - 18
    - 21
    - 24
    - 36
    - 48
    - 54
    - 60
    - 66
    - 72
    - 78
    - 84
    - 96
    - 108
    - 120
    - 132
    - 144
    - 168
    - 192
